customhost = "employee.cwet0oizhsij.ap-south-1.rds.amazonaws.com"
customuser = "rambabu5441"
custompass = "rambabu5441"
customdb = "employee"
custombucket = "employeebucket5441"
customregion = "ap-south-1"
